name: Integration test

on:
  push:
    branches:
      - main
  schedule:
    # Every month
    - cron:  '11 11 11 * *'

jobs:
  terraform-download-job:
    runs-on: ubuntu-latest
    name: Downloading Terraform state
    steps:
      - id: state-download
        uses: devgioele/terraform-state-artifact@v3
        with:
          passphrase: ${{ secrets.TF-STATE-PASSPHRASE }}
          download-upload: download
  terraform-upload-job:
    runs-on: ubuntu-latest
    name: Uploading Terraform state
    steps:
      - id: state-upload
        uses: devgioele/terraform-state-artifact@v3
        with:
          encryption-key: ${{ secrets.pat }}
          download-upload: upload